// <auto-generated />
using System;
using FastBiteGroupMCA.Persistentce;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastBiteGroupMCA.Persistentce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.AdminAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("AdminFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetEntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetEntityType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.AdminNotifications", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LinkTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredByUserId");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.ContentReport", b =>
                {
                    b.Property<int>("ContentReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentReportID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ReportedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReportedContentID")
                        .HasColumnType("int");

                    b.Property<Guid>("ReportedContentOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportedContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ContentReportID");

                    b.HasIndex("GroupID");

                    b.HasIndex("ReportedByUserID");

                    b.ToTable("ContentReports", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationID"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ConversationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExplicitGroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastMessagePreview")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastMessageSenderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastMessageTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversationID");

                    b.HasIndex("ExplicitGroupID")
                        .IsUnique()
                        .HasFilter("[ExplicitGroupID] IS NOT NULL");

                    b.ToTable("Conversations", (string)null);

                    b.HasData(
                        new
                        {
                            ConversationID = 1,
                            AvatarUrl = "https://your-cdn.com/default-group-avatar.png",
                            ConversationType = "Group",
                            CreatedAt = new DateTime(2025, 9, 21, 16, 53, 32, 122, DateTimeKind.Utc).AddTicks(7366),
                            ExplicitGroupID = new Guid("e2a8b9c7-d3f4-4a6b-9c8d-10ffbca9876f"),
                            IsDeleted = false,
                            Title = "Nhóm Chat Công khai"
                        });
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.ConversationParticipants", b =>
                {
                    b.Property<int>("ConversationParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationParticipantID"));

                    b.Property<int>("ConversationID")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReadTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConversationParticipantID");

                    b.HasIndex("UserID");

                    b.HasIndex("ConversationID", "UserID")
                        .IsUnique();

                    b.ToTable("ConversationParticipants", (string)null);

                    b.HasData(
                        new
                        {
                            ConversationParticipantID = 2,
                            ConversationID = 1,
                            IsArchived = false,
                            IsMuted = false,
                            JoinedAt = new DateTime(2025, 9, 21, 16, 53, 32, 122, DateTimeKind.Utc).AddTicks(7462),
                            UserID = new Guid("d1f9aeb8-e2c3-4b5a-8d6f-09eecba8765e")
                        });
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.GlobalSettings", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingKey");

                    b.ToTable("GlobalSettings");

                    b.HasData(
                        new
                        {
                            SettingKey = "SiteName",
                            SettingValue = "FastBite MCA"
                        },
                        new
                        {
                            SettingKey = "MaintenanceMode",
                            SettingValue = "false"
                        },
                        new
                        {
                            SettingKey = "AllowNewRegistrations",
                            SettingValue = "true"
                        },
                        new
                        {
                            SettingKey = "RequireEmailConfirmation",
                            SettingValue = "true"
                        },
                        new
                        {
                            SettingKey = "DefaultRoleForNewUsers",
                            SettingValue = "Customer"
                        },
                        new
                        {
                            SettingKey = "ForbiddenKeywords",
                            SettingValue = ""
                        },
                        new
                        {
                            SettingKey = "AutoLockAccountThreshold",
                            SettingValue = "0"
                        },
                        new
                        {
                            SettingKey = "MaxFileSizeMb",
                            SettingValue = "10"
                        },
                        new
                        {
                            SettingKey = "MaxAvatarSizeMb",
                            SettingValue = "2"
                        },
                        new
                        {
                            SettingKey = "AllowedFileTypes",
                            SettingValue = "jpg,jpeg,png,gif,pdf,docx,xlsx,zip"
                        },
                        new
                        {
                            SettingKey = "AllowedAvatarTypes",
                            SettingValue = "jpg,jpeg,png,gif"
                        });
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GroupAvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Privacy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupID");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedByUserID");

                    b.ToTable("Groups", (string)null);

                    b.HasData(
                        new
                        {
                            GroupID = new Guid("e2a8b9c7-d3f4-4a6b-9c8d-10ffbca9876f"),
                            CreatedAt = new DateTime(2025, 9, 21, 16, 53, 32, 122, DateTimeKind.Utc).AddTicks(7317),
                            CreatedByUserID = new Guid("c0e8fad7-d01b-483c-bf0d-08ddc9b9460d"),
                            Description = "Đây là một nhóm được tạo sẵn để thảo luận.",
                            GroupAvatarUrl = "https://your-cdn.com/default-group-avatar.png",
                            GroupName = "Nhóm Chat Công khai",
                            GroupType = "Public",
                            IsArchived = false,
                            IsDeleted = false,
                            Privacy = "Public",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.GroupInvitations", b =>
                {
                    b.Property<int>("InvitationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("InvitationID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("GroupID");

                    b.HasIndex("InvitationCode")
                        .IsUnique();

                    b.ToTable("GroupInvitations", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberID"));

                    b.Property<Guid>("GroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupMemberID");

                    b.HasIndex("UserID");

                    b.HasIndex("GroupID", "UserID")
                        .IsUnique();

                    b.ToTable("GroupMembers", (string)null);

                    b.HasData(
                        new
                        {
                            GroupMemberID = 2,
                            GroupID = new Guid("e2a8b9c7-d3f4-4a6b-9c8d-10ffbca9876f"),
                            JoinedAt = new DateTime(2025, 9, 21, 16, 53, 32, 122, DateTimeKind.Utc).AddTicks(7432),
                            Role = "Member",
                            UserID = new Guid("d1f9aeb8-e2c3-4b5a-8d6f-09eecba8765e")
                        });
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            ConcurrencyStamp = "9f791064-36bd-4af6-8192-7769c123193b",
                            IsSystemRole = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-2345-67890abcdef1"),
                            ConcurrencyStamp = "9f791064-36bd-4af6-8192-7769c123193b",
                            IsSystemRole = true,
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = new Guid("e2a9bfc7-d3f4-4a6b-9c8d-10ffbca9876e"),
                            ConcurrencyStamp = "9f791064-36bd-4af6-8192-7769c123193b",
                            IsSystemRole = true,
                            Name = "VIP",
                            NormalizedName = "VIP"
                        });
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FisrtName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessagingPrivacy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OneSignalPlayerId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PresenceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0e8fad7-d01b-483c-bf0d-08ddc9b9460d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0fd7ab16-c716-4985-8420-b9e0e8821dd8",
                            CreatedAt = new DateTime(2025, 9, 21, 16, 53, 32, 84, DateTimeKind.Utc).AddTicks(832),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "superadmin@app.com",
                            EmailConfirmed = true,
                            FisrtName = "Super",
                            FullName = "Super Admin",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            MessagingPrivacy = "FromSharedGroupMembers",
                            NormalizedEmail = "SUPERADMIN@APP.COM",
                            NormalizedUserName = "SUPERADMIN@APP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMh7x7zHRm5zXjhhH4t4+Bp2HgzmLb9pnIFl9MaGvHyKFTui5l9WpyCCMcggOC0dNQ==",
                            PhoneNumberConfirmed = false,
                            PresenceStatus = "Offline",
                            RowVersion = new byte[0],
                            SecurityStamp = "fd7d18eb-2d34-4249-8033-f1b2397d85a1",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@app.com"
                        },
                        new
                        {
                            Id = new Guid("d1f9aeb8-e2c3-4b5a-8d6f-09eecba8765e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c08da64f-9c0a-4951-b675-f56f6f48bb70",
                            CreatedAt = new DateTime(2025, 9, 21, 16, 53, 32, 122, DateTimeKind.Utc).AddTicks(6823),
                            DateOfBirth = new DateTime(2000, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testuser@app.com",
                            EmailConfirmed = true,
                            FisrtName = "Test",
                            FullName = "Test User",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "User",
                            LockoutEnabled = false,
                            MessagingPrivacy = "FromSharedGroupMembers",
                            NormalizedEmail = "TESTUSER@APP.COM",
                            NormalizedUserName = "TESTUSER@APP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOZloerFRtzAqd0c91XhgjLmFVHn81jQ6UMI7jwUjTff3ye+Vm/e9Gdpg63bcwfWJw==",
                            PhoneNumberConfirmed = false,
                            PresenceStatus = "Offline",
                            RowVersion = new byte[0],
                            SecurityStamp = "48b01ae4-c117-4ff2-8314-b5a9750fc4da",
                            TwoFactorEnabled = false,
                            UserName = "testuser@app.com"
                        });
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.LoginHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PollOptions", b =>
                {
                    b.Property<int>("PollOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PollOptionID"));

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PollID")
                        .HasColumnType("int");

                    b.HasKey("PollOptionID");

                    b.HasIndex("PollID");

                    b.ToTable("PollOptions", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PollVotes", b =>
                {
                    b.Property<long>("PollVoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PollVoteID"));

                    b.Property<int>("PollOptionID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PollVoteID");

                    b.HasIndex("UserID");

                    b.HasIndex("PollOptionID", "UserID")
                        .IsUnique();

                    b.ToTable("PollVotes", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Polls", b =>
                {
                    b.Property<int>("PollID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PollID"));

                    b.Property<bool>("AllowMultipleChoices")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConversationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MessageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("PollID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("CreatedByUserID");

                    b.ToTable("Polls", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PostAttachment", b =>
                {
                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<int>("FileID")
                        .HasColumnType("int");

                    b.HasKey("PostID", "FileID");

                    b.HasIndex("FileID");

                    b.ToTable("PostAttachments", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PostComments", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentID")
                        .HasColumnType("int");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentID");

                    b.HasIndex("ParentCommentID");

                    b.HasIndex("PostID");

                    b.HasIndex("UserID");

                    b.ToTable("PostComments", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PostLikes", b =>
                {
                    b.Property<long>("LikeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LikeID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LikeID");

                    b.HasIndex("UserID");

                    b.HasIndex("PostID", "UserID")
                        .IsUnique();

                    b.ToTable("PostLikes", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Posts", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostID"));

                    b.Property<Guid>("AuthorUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PostID");

                    b.HasIndex("AuthorUserID");

                    b.HasIndex("GroupID", "CreatedAt")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            AuthorUserID = new Guid("c0e8fad7-d01b-483c-bf0d-08ddc9b9460d"),
                            ContentHtml = "<p>Đây là bài viết đầu tiên trong nhóm.</p>",
                            ContentJson = "{\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"Đây là bài viết đầu tiên trong nhóm.\"}]}]}",
                            CreatedAt = new DateTime(2025, 9, 21, 16, 53, 32, 122, DateTimeKind.Utc).AddTicks(7511),
                            GroupID = new Guid("e2a8b9c7-d3f4-4a6b-9c8d-10ffbca9876f"),
                            IsDeleted = false,
                            IsPinned = true,
                            Status = 1,
                            Title = "Chào mừng đến với ứng dụng!"
                        });
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.SharedFiles", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileID"));

                    b.Property<string>("FileContext")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FileID");

                    b.HasIndex("UploadedByUserID");

                    b.ToTable("SharedFiles", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.UserGroupInvitation", b =>
                {
                    b.Property<int>("InvitationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvitedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvitedUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvitationID");

                    b.HasIndex("GroupID");

                    b.HasIndex("InvitedByUserID");

                    b.HasIndex("InvitedUserID", "GroupID")
                        .IsUnique()
                        .HasDatabaseName("IX_Unique_User_Group_Invitation");

                    b.ToTable("UserGroupInvitations", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.VideoCallParticipants", b =>
                {
                    b.Property<int>("VideoCallParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoCallParticipantID"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VideoCallSessionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VideoCallParticipantID");

                    b.HasIndex("UserID");

                    b.HasIndex("VideoCallSessionID", "UserID")
                        .IsUnique();

                    b.ToTable("VideoCallParticipants", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.VideoCallSessions", b =>
                {
                    b.Property<Guid>("VideoCallSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("ConversationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InitiatorUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeoutJobId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("VideoCallSessionID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("InitiatorUserID");

                    b.ToTable("VideoCallSessions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c0e8fad7-d01b-483c-bf0d-08ddc9b9460d"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef")
                        },
                        new
                        {
                            UserId = new Guid("d1f9aeb8-e2c3-4b5a-8d6f-09eecba8765e"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-2345-67890abcdef1")
                        },
                        new
                        {
                            UserId = new Guid("c0e8fad7-d01b-483c-bf0d-08ddc9b9460d"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-2345-67890abcdef1")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.AdminAuditLog", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.AdminNotifications", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "TriggeredByUser")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId");

                    b.Navigation("TriggeredByUser");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.ContentReport", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Group", "Group")
                        .WithMany("ContentReports")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "ReportedByUser")
                        .WithMany("ContentReports")
                        .HasForeignKey("ReportedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Group", "Group")
                        .WithOne()
                        .HasForeignKey("FastBiteGroupMCA.Domain.Entities.Conversation", "ExplicitGroupID");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.ConversationParticipants", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("ConversationParticipations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Group", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId");

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "CreatedByUser")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.GroupInvitations", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "CreatedByUser")
                        .WithMany("CreatedGroupInvitations")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Group", "Group")
                        .WithMany("GroupInvitations")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.LoginHistory", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PollOptions", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Polls", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PollVotes", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.PollOptions", "PollOption")
                        .WithMany("Votes")
                        .HasForeignKey("PollOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("PollVotes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PollOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Polls", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "CreatedByUser")
                        .WithMany("CreatedPolls")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PostAttachment", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.SharedFiles", "SharedFile")
                        .WithMany()
                        .HasForeignKey("FileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Posts", "Post")
                        .WithMany("Attachments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("SharedFile");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PostComments", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.PostComments", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentID");

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Posts", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("PostComments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PostLikes", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Posts", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Posts", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "Author")
                        .WithMany("AuthoredPosts")
                        .HasForeignKey("AuthorUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Group", "Group")
                        .WithMany("Posts")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId");

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.SharedFiles", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "UploadedByUser")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.UserGroupInvitation", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Group", "Group")
                        .WithMany("DirectUserInvitations")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "InvitedByUser")
                        .WithMany("SentInvitations")
                        .HasForeignKey("InvitedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "InvitedUser")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("InvitedUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.VideoCallParticipants", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("VideoCallParticipations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.VideoCallSessions", "VideoCallSession")
                        .WithMany("Participants")
                        .HasForeignKey("VideoCallSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VideoCallSession");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.VideoCallSessions", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", "UserInitiator")
                        .WithMany("InitiatedVideoCallSessions")
                        .HasForeignKey("InitiatorUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("UserInitiator");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Group", b =>
                {
                    b.Navigation("ContentReports");

                    b.Navigation("DirectUserInvitations");

                    b.Navigation("GroupInvitations");

                    b.Navigation("Members");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Identity.AppUser", b =>
                {
                    b.Navigation("AuthoredPosts");

                    b.Navigation("ContentReports");

                    b.Navigation("ConversationParticipations");

                    b.Navigation("CreatedGroupInvitations");

                    b.Navigation("CreatedGroups");

                    b.Navigation("CreatedPolls");

                    b.Navigation("GroupMemberships");

                    b.Navigation("InitiatedVideoCallSessions");

                    b.Navigation("PollVotes");

                    b.Navigation("PostComments");

                    b.Navigation("PostLikes");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SentInvitations");

                    b.Navigation("UploadedFiles");

                    b.Navigation("VideoCallParticipations");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PollOptions", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Polls", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.PostComments", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.Posts", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("FastBiteGroupMCA.Domain.Entities.VideoCallSessions", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
